# Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/mixpanel/MessageStore.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/MessageThread.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/MessageWorker.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/Mixpanel.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/Preferences.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/mixpanel_query.c)

        HEADERS +=  $$quote($$BASEDIR/src/mixpanel/MessageStore.h) \
                 $$quote($$BASEDIR/src/mixpanel/MessageThread.h) \
                 $$quote($$BASEDIR/src/mixpanel/MessageWorker.h) \
                 $$quote($$BASEDIR/src/mixpanel/Mixpanel.h) \
                 $$quote($$BASEDIR/src/mixpanel/Preferences.h) \
                 $$quote($$BASEDIR/src/mixpanel/mixpanel_endpoint.h) \
                 $$quote($$BASEDIR/src/mixpanel/mixpanel_query.h)
    }

    CONFIG(release, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/mixpanel/MessageStore.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/MessageThread.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/MessageWorker.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/Mixpanel.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/Preferences.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/mixpanel_query.c)

        HEADERS +=  $$quote($$BASEDIR/src/mixpanel/MessageStore.h) \
                 $$quote($$BASEDIR/src/mixpanel/MessageThread.h) \
                 $$quote($$BASEDIR/src/mixpanel/MessageWorker.h) \
                 $$quote($$BASEDIR/src/mixpanel/Mixpanel.h) \
                 $$quote($$BASEDIR/src/mixpanel/Preferences.h) \
                 $$quote($$BASEDIR/src/mixpanel/mixpanel_endpoint.h) \
                 $$quote($$BASEDIR/src/mixpanel/mixpanel_query.h)
    }
}

simulator {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/mixpanel/MessageStore.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/MessageThread.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/MessageWorker.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/Mixpanel.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/Preferences.cpp) \
                 $$quote($$BASEDIR/src/mixpanel/mixpanel_query.c)

        HEADERS +=  $$quote($$BASEDIR/src/mixpanel/MessageStore.h) \
                 $$quote($$BASEDIR/src/mixpanel/MessageThread.h) \
                 $$quote($$BASEDIR/src/mixpanel/MessageWorker.h) \
                 $$quote($$BASEDIR/src/mixpanel/Mixpanel.h) \
                 $$quote($$BASEDIR/src/mixpanel/Preferences.h) \
                 $$quote($$BASEDIR/src/mixpanel/mixpanel_endpoint.h) \
                 $$quote($$BASEDIR/src/mixpanel/mixpanel_query.h)
    }
}

INCLUDEPATH +=  $$quote($$BASEDIR/src/mixpanel)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../src/*.c) \
             $$quote($$BASEDIR/../src/*.c++) \
             $$quote($$BASEDIR/../src/*.cc) \
             $$quote($$BASEDIR/../src/*.cpp) \
             $$quote($$BASEDIR/../src/*.cxx) \
             $$quote($$BASEDIR/../assets/*.qml) \
             $$quote($$BASEDIR/../assets/*.js) \
             $$quote($$BASEDIR/../assets/*.qs)

    HEADERS +=  $$quote($$BASEDIR/../src/*.h) \
             $$quote($$BASEDIR/../src/*.h++) \
             $$quote($$BASEDIR/../src/*.hh) \
             $$quote($$BASEDIR/../src/*.hpp) \
             $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS =  $$quote($${TARGET}.ts)
